### ISSUE TITLE
Build error: ‘int64_t’ has not been declared

### ISSUE THREAD

**Issue by ajhwb** [mbientlab/Metawear-CppAPI#10]
Hi, got this when compiling on x86

g++ = g++ (Debian 4.7.2-5) 4.7.2
make = GNU Make 3.81
Linux elena 3.10.17-yocto-standard-r2 #7 SMP PREEMPT Thu Feb 26 09:57:06 UTC 2015 i686 GNU/Linux

$ make
mkdir -p build/x86/release/src/metawear/platform/cpp
mkdir -p build/x86/release/src/metawear/core/cpp
mkdir -p build/x86/release/src/metawear/peripheral/cpp
mkdir -p build/x86/release/src/metawear/processor/cpp
mkdir -p build/x86/release/src/metawear/sensor/cpp
mkdir -p build/x86/release/src/metawear/impl/cpp
mkdir -p dist/release/lib/x86
g++ -MMD -MP -MF "build/x86/release/src/metawear/platform/cpp/threadpool.d" -c -o build/x86/release/src/metawear/platform/cpp/threadpool.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -O3 -m32 src/metawear/platform/cpp/threadpool.cpp
In file included from src/metawear/platform/cpp/threadpool.cpp:1:0:
src/metawear/platform/cpp/threadpool.h:8:57: error: ‘int64_t’ has not been declared
src/metawear/platform/cpp/threadpool.cpp:30:7: error: prototype for ‘Task* ThreadPool::schedule(std::function<void()>, int64_t)’ does not match any in class ‘ThreadPool’
In file included from src/metawear/platform/cpp/threadpool.cpp:1:0:
src/metawear/platform/cpp/threadpool.h:8:18: error: candidate is: static Task* ThreadPool::schedule(std::function<void()>, int)
make: *** [build/x86/release/src/metawear/platform/cpp/threadpool.o] Error 1

**Comment by scaryghost** [comment]
Add an include for stdint.h in threadpool.h.  It appears that later gcc compilers and vs2015 can fill in the size requirements for you.

**Comment by ajhwb** [comment]
Build was succeeded after adding stdint.h in src/metawear/platform/cpp/threadpool.h
FYI, I don't have this issue in API version < 0.5.0

Should I close this?

**Comment by scaryghost** [comment]
That specific file isn't present in the earlier builds.
