### ISSUE TITLE
Timeout status in board mbl_mw_metawearboard_initialize()

### ISSUE THREAD

**Issue by ajhwb** [mbientlab/Metawear-CppAPI#11]
Hi,

Host: Linux 3.10.17-yocto-standard-r2 #7 SMP PREEMPT Thu Feb 26 09:57:06 UTC 2015 i686 GNU/Linux
SDK: 0.5.0 (most recent commit)

Most of times I get `MBL_MW_STATUS_ERROR_TIMEOUT (16)` status when calling `mbl_mw_metawearboard_initialize()`. I didn't have this issue in 0.4.15

This API was changed from 0.4.15
`void mbl_mw_metawearboard_initialize(MblMwMetaWearBoard *board, MblMwFnVoid initialized)`

0.5.0

`void mbl_mw_metawearboard_initialize(MblMwMetaWearBoard *board, MblMwFnBoardPtrInt initialized)`

This is the application logs:

```
ardhan@clarence:~/Metawear-Cpp-Driver/cpro-driver$ ./cpro-driver_experimental device.conf 
Device C0:69:B0:46:03:B5 was connected
write_gatt_char: handle=0x001d uuid=326a9001-85cb-9195-d9dd-464cfbbae75a
write_gatt_char: value: 11 09 08 00 80 0c 00 00 d0 07 
read_gatt_char: handle=0x001a uuid=00002a26-0000-1000-8000-00805f9b34fb
Characteristic value/descriptor: 31 2e 32 2e 33 
read_gatt_char: handle=0x0014 uuid=00002a24-0000-1000-8000-00805f9b34fb
Characteristic value/descriptor: 32 
write_gatt_char: handle=0x001d uuid=326a9001-85cb-9195-d9dd-464cfbbae75a
write_gatt_char: value: 01 80 
[ERROR] 2016-09-13_03:59:01.554: Initialization failed (16)...!
```

**Comment by scaryghost** [comment]
See issue #9
