### ISSUE TITLE
Sensor data signal handler stopped being called

### ISSUE THREAD

**Issue by ajhwb** [mbientlab/Metawear-CppAPI#12]
Firmware: 1.2.4
C++ SDK: 5.22
Host: Linux 3.10
BlueZ: 5.39

After several minutes running our program which subscribes to a CPRO accelerometer, gyro and magnetometer sensors, apparently it stop receiving sensor data, in this case all signal handlers were stopped being called. We have had this issue since the previous firmware and SDK. With device reset, the stream shall run again then unfortunately stop after some times.

We tested using latest 1.2.4 firmware since as the release notes say it may have addressed this issue. I believe the problem is identical to this post http://community.mbientlab.com/discussion/1773/board-stops-sending-data-after-few-sequential-connect-disconnect-cycles-possibly-a-firmware-bug#latest

**Comment by scaryghost** [comment]
This is not an issue related to the C++ API.  We can continue the discussion in the aforementioned thread.
