### ISSUE TITLE
Battery state query generates Out of Range exception 

### ISSUE THREAD

**Issue by hbldh** [mbientlab/Metawear-CppAPI#2]
Using the new 0.4.0 API, I tried one of the new battery state methods out. I called the built shared library from Python, in a similar fashion to the tests for this library; see [usage for my Python MetaWear client](https://github.com/hbldh/pymetawear#usage).

Reading battery state with
```python
libmetawear.mbl_mw_settings_read_battery_state(board)
```

leads to exception in, I think, the C++ library:

```cpp
terminate called after throwing an instance of 'std::out_of_range'
    what():  _Map_base::at
```

Other points of interest:
* System is running Ubuntu 15.10
* The Python tests for Metawear-CppAPI passes. 
* The Metawear-CppAPI is built with gcc 5.2.1
* I can flash the LEDs using the same approach, both in Python 2.7.10 and Python 3.4.3.

**Comment by scaryghost** [comment]
The out_of_range exception appears to be raised in [settings.cpp:103](https://github.com/mbientlab/Metawear-CppAPI/blob/0.4.0/src/metawear/core/cpp/settings.cpp#L103).    That can only happen functions are being called before **mbl_mw_metawearboard_initialize** is completed.  Is this [print statement](https://github.com/hbldh/pymetawear/blob/v0.1.0/pymetawear/client.py#L108) in your Python code being called?

**Comment by scaryghost** [comment]
Forgot to mention, what firmware are your boards running?  Reading battery state through the API is only supported on firmware v1.1.1 and later.

**Comment by hbldh** [comment]
No, now that you mention it, that print does not show up in any output. But I can communicate with the board and flash the LEDs, even though the initialization is not complete?

Both my boards were upgraded to firmware version 1.1.3 prior to the tests.

**Comment by scaryghost** [comment]
Some modules, such as Led, will still work regardless of the library being initialized.  Others, like sensors, need to the library to be initialized as different MetaWear boards have different sensors.

In your Python code, you need to forward btle responses to the library as outlined in [this section](https://github.com/mbientlab/Metawear-CppAPI/wiki/API-v0.3.0-How-To#handling-responses) on the HowTo wiki page.

**Comment by hbldh** [comment]
I see; I need to fix it up somewhat. The "*enable notifications on that characteristic*" means some kind of subscription to data from that characteristic and will then need some threading at least?

This issue might be closed then, and further discussion regarding this can be held in the forum.
