### ISSUE TITLE
Proposal to use relative imports in functions.py

### ISSUE THREAD

**Issue by hbldh** [mbientlab/Metawear-CppAPI#3]
The new `functions.py` module imports using [absolute paths](https://github.com/mbientlab/Metawear-CppAPI/blob/master/wrapper/python/mbientlab/metawear/functions.py#L4-L6), which makes it a requirement to have the `mbientlab` package as a root package in the Python path (as is done in the [Makefile](https://github.com/mbientlab/Metawear-CppAPI/blob/master/Makefile#L89)). 

In my Python package, I instead include this repository as a Git submodule and copy the entire `mbientlab` package so it becomes a subpackage (`pymetawear.mbientlab`). Importing the `functions` module fails in that case. I propose the following import compromise using relative imports:
```python
from ctypes import *
from .core import *
from .peripheral import Led
```
The MetaWear-CppAPI tests still pass and I can use the `setup_libmetawear` method without modifying the `functions.py` file.

I would have sent a pull request, but since it said that the file was autogenerated I felt it better to add this as an improvement issue.

**Comment by scaryghost** [comment]
Done
