### ISSUE TITLE
Problem with Magnetometer

### ISSUE THREAD

**Issue by AlexDmr** [mbientlab/Metawear-CppAPI#4]
Hi,
I got a metawear C, I am able to abserve accelerometer, gyroscope and button but I can not access to the magnetometer (I got no notification from it)...
Here are the code I send to the codes that I send to it : 
  - 0x15040102
  - 0x150300
  - 0x15020100
  - 0x150101

P.S. 1 : I am pretty sure that the magnetometer works (tested with the android App).
P.S. 2 : Btw : there is a typo on the python test for magnetomter, you define twice the test start_accelerometer, the second time should be about stop_accelerometer.

**Comment by scaryghost** [comment]
You need to subscribe to the signal to receive a live stream.

**Comment by AlexDmr** [comment]
Indeed, I forgot to send the subscribe command :  
0x150501

I am implementing a nodeJS library that use Metaware. Is there any other do than the C++ coe (or Android one) to find out what are the command to send ?

**Comment by scaryghost** [comment]
No, those are the only two places that document the byte strings.
