### ISSUE TITLE
Building on Raspberry Pi

### ISSUE THREAD

**Issue by hbldh** [mbientlab/Metawear-CppAPI#7]
I have tried to get the library to build on my Raspberry Pi 2, i.e. on ARM architecture, with little success so far. 

For starters, the `-m32`/`-m64` does not work there, and after removal of them from Makefile it at least builds. Running the `make test` command yields the following output:

```
pi@raspberrypi:~/Repos/Metawear-CppAPI $ make test
python3 -m unittest discover -s test
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Makefile:117: recipe for target 'test' failed
make: *** [test] Aborted
```
I have tried several other flags (The Rasbian Jessie image has `gcc (Raspbian 4.9.2-10) 4.9.2` as default so I was looking through the [manual](https://gcc.gnu.org/onlinedocs/gcc-4.9.2/gcc/ARM-Options.html#ARM-Options)), but also without success. Have tried building with Clang as well, but the apt-get package of it is this:
```
Raspbian clang version 3.5.0-10+rpi1 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
Target: arm-unknown-linux-gnueabihf
Thread model: posix
```

Do you have any idea as to what might be done to get it to run? This error is similar to the one in #2, is the cause similar as well do you think?

**Comment by brianhouse** [comment]
I'm experiencing this same issue, on a Pi 3.

**Comment by scaryghost** [comment]
- Do you only run into this issue on the Raspbian build?  I don't have any issues when executing the unit tests on Ubuntu with gcc 4.9.2 and python 3.4.3.
- Can you run the unit tests with the `-v` flag and let me know which test failed?

**Comment by brianhouse** [comment]
```
pi@raspberrypi:~/Metawear-CppAPI $ make test
python3 -m unittest discover -s test -v
test_acc_bma255_disable_acceleration_sampling (testaccelerometer.TestGenericAccelerometerBma255) ... terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Makefile:97: recipe for target 'test' failed
make: *** [test] Aborted
```

I haven't tried other builds, are you saying this works with Ubuntu on the Pi?

**Comment by hbldh** [comment]
No, I have not encountered this on any other place than on a Raspberry. All builds on Ubuntu on x86 or x86_64 have worked for me.

Tried building with clang 3.7 on same machine, yielded different errors:
```
======================================================================
ERROR: setUpClass (testtimer.TestTimerTimeout)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/Repos/Metawear-CppAPI/test/common.py", line 18, in setUpClass
    cls.libmetawear= CDLL(os.environ["METAWEAR_LIB_SO_NAME"])
  File "/usr/lib/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dist/release/lib/arm/libmetawear.so.0.5.0: undefined symbol: __cxa_pure_virtual
```
Got a lot of these instead; at least not a segfault...

**Comment by scaryghost** [comment]
The `__cxa_pure_virtual` function is provided by libstdc++.  If you're building with clang and not clang++, it is probably not linking against libstdc++.

**Comment by hbldh** [comment]
Ah, of course.

Compiling with
```
make CXX=clang++-3.7
```
creates the same error as above. Sorry.

**Comment by scaryghost** [comment]
Well, it would seem that whatever libstdc++ is on the Raspbian build doesn't have `__cxa_pure_virtual` defined.  You can add it into the code to see if that fixes this problem.

Switching back to gcc, since you can load the library into Python, can you add this print statement to line 242 in [common.py](https://github.com/mbientlab/Metawear-CppAPI/blob/0.5.0/test/common.py#L242) and copy what is echoed up to the crash?

```python
print(self.command)
```

**Comment by hbldh** [comment]
Added print statement as you instructed, but it never arrives at it apparently since nothing is printed out. Hunted it down to [testaccelerometer.py](https://github.com/hbldh/Metawear-CppAPI/blob/master/test/testaccelerometer.py#L189) where I could surround this call with print statements and only have the one prior to the call printed.

I removed that function to see what happened with the tests then and got the following output:
```
pi@raspberrypi:~/Repos/Metawear-CppAPI $ make test
python3 -m unittest discover -s test -v
test_disable_acceleration_sampling (testaccelerometer_bma255.TestAccBma255Config) ... [3, 2, 0, 1]
ok
test_enable_acceleration_sampling (testaccelerometer_bma255.TestAccBma255Config) ... [3, 2, 1, 0]
ok
test_set_odr (testaccelerometer_bma255.TestAccBma255Config) ... terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Makefile:117: recipe for target 'test' failed
make: *** [test] Aborted

```

So, using the generic function `mbl_mw_acc_disable_acceleration_sampling`, it crashes, but when using the model specific call `mbl_mw_acc_bosch_disable_acceleration_sampling`, it works fine. Does this indicate that something with accessing the sent in board's details creates the segfault?

**Comment by scaryghost** [comment]
Based on your previous post, it would seem like the API is not being initialized in the unit test.  A quick way to check is to surround the `mbl_mw_metawearboard_initialize` function with print statements in [common.py:L209](https://github.com/mbientlab/Metawear-CppAPI/blob/0.5.0/test/common.py#L209) and print out the `status` variable in [common.py:L221](https://github.com/mbientlab/Metawear-CppAPI/blob/0.5.0/test/common.py#L221)

**Comment by hbldh** [comment]
Results:
```
python3 -m unittest discover -s test
setUp: Pre-Init /** Before L209 **/
setUp: Post-Init /** After L209 **/
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Makefile:99: recipe for target 'test' failed
make: *** [test] Aborted
```
The print statements surrounding L209 gets executed, but nothing is executed in the `initialized` function in L221.

**Comment by scaryghost** [comment]
OK that's really bizarre then.  It seems like the either the `mbl_mw_metawearboard_initialize` function is not being called or it is but the function pointers in the BtleConnection struct are never accessed.

**Comment by hbldh** [comment]
Adding some printout debugging in the C++ code, trying to find something. All prints in the `mbl_mw_metawearboard_initialize` function (one after each statement) is being executed.

Digging through some forums for threading problems on arm architecture (http://stackoverflow.com/a/23597422 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=62100) I am now trying to build with specifying architecture corresponding to the `gcc` version on the Raspberry. Will share results later.

**Comment by hbldh** [comment]
Not success so far, with anything. 

The `mbl_mw_metawearboard_initialize` function is called and all functions therein is executed. It halts at the sleep at [threadpool.cpp:L34](https://github.com/mbientlab/Metawear-CppAPI/blob/master/src/metawear/platform/cpp/threadpool.cpp#L34) and never gets past that prior to crashing.

**Comment by scaryghost** [comment]
Threadpool stuff executes on a different thread so that's fine.  The `queue_next_gatt_char` function, [metawearboard.cpp:272](https://github.com/mbientlab/Metawear-CppAPI/blob/0.5.0/src/metawear/impl/cpp/metawearboard.cpp#L272) should call the `read_gatt_char` function pointer, which should be visible in [common.py:L223](https://github.com/mbientlab/Metawear-CppAPI/blob/0.5.0/test/common.py#L223).

**Comment by scaryghost** [comment]
Did the previous release work on the Pi?  If so, then it could be the use of the C++11 threads that's causing the problem.

**Comment by hbldh** [comment]
No, I have never gotten it to compile on my raspberry. Tried it briefly on the old Raspbian OS based on Debian Wheezy and never got it to work there. Checked out old tags now and tried them as well, and it did not work either.

**Comment by hbldh** [comment]
Added printout when entering `read_gatt_char` in [common.py:L224](https://github.com/mbientlab/Metawear-CppAPI/blob/0.5.0/test/common.py#L224), printing the characteristics that are to be read during initialization.

Added 
```
print("Char: {0} {1}".format(hex(characteristic.contents.uuid_high), hex(characteristic.contents.uuid_low)))
```

Building and running tests on the Rapsberry Pi gives
```
Char: 0x5f9b34fb 0x80000080
```

On my x64 system the same change yields
```
Char: 0x2a2600001000 0x800000805f9b34fb
```
So, I believe that something is wrong with the 64-bit int representation of characteristic addresses. Will look further later tonight.

**Comment by hbldh** [comment]
Could not refrain from some more testing...

I believe the fact that `long` on the [Raspberry is a 32-bit value](http://www.raspberry-projects.com/pi/programming-in-c/memory/variables) is the culprit.

Changing [Epoch and GattCharacterstics](https://github.com/mbientlab/Metawear-CppAPI/blob/master/wrapper/python/mbientlab/metawear/core.py#L40-L55) values to be of C type `longlong` instead makes all but one unit test pass: [`test_unknown_entry` in `testlogging.py`](https://github.com/mbientlab/Metawear-CppAPI/blob/master/test/testlogging.py#L119-L124). It creates a segmentation fault:

```
test_unknown_entry (testlogging.TestLogDownload) ... 
Char: 0x2a2600001000 0x800000805f9b34fb
Char: 0x2a2400001000 0x800000805f9b34fb
initialized: Board: 26701304 status: 0
Makefile:107: recipe for target 'test' failed
make: *** [test] Segmentation fault
```
Have you got any idea as to why that particular test fails? 

How do you think this discovery can be integrated in MetaWear-CppAPI? The use of `c_longlong` instead of `c_long` in the Python wrapper should not create any problems on x86 and x86_64 machines, am I right?

**Comment by scaryghost** [comment]
Ah I see, the classic int/long sizing across different architectures.  The [ctypes](https://docs.python.org/3/library/ctypes.html#fundamental-data-types) page states that `c_long` is equivalent to a long type in C so `c_longlong` would be the correct typing as that struct is holding 8 byte variables.  

The `test_unknown_entry` is the same issue as that `CFUNCTYPE` definition also uses `c_long`.

**Comment by hbldh** [comment]
Created a pull request with the changes that makes build and test succeed on my Raspberry Pi 2. I refrained from renaming `Fn_Ubyte_Long_ByteArray` to `Fn_Ubyte_LongLong_ByteArray` even though I think it would be more prudent; not my decision to make.

@brianhouse Can you try to build and test [my fork, branch feature/longlong_fix](https://github.com/hbldh/Metawear-CppAPI) on your Raspberry Pi 3 as well to confirm that it works there as well?

**Comment by brianhouse** [comment]
works!

```
Ran 309 tests in 7.604s

OK
```
