### ISSUE TITLE
Make `TIME_PER_COMMAND` a parameter instead of a constant

### ISSUE THREAD

**Issue by hbldh** [mbientlab/Metawear-CppAPI#9]
In [src/metawear/core/cpp/constant.h](https://github.com/mbientlab/Metawear-CppAPI/blob/master/src/metawear/core/cpp/constant.h#L6) the value is hard coded to 150. This value is used in [`mbl_mw_metawearboard_initialize`](https://github.com/mbientlab/Metawear-CppAPI/blob/master/src/metawear/impl/cpp/metawearboard.cpp#L269-L271) and makes the initialization fail when I use the library.

During the writing and notification exchange during initialization I get a [status 16](https://github.com/mbientlab/Metawear-CppAPI/blob/master/src/metawear/core/status.h#L22) response and initialization breaks. When changing the value to >250, then everything works fine and initialization is completed successfully.

Is it possible to make `TIME_PER_COMMAND` into parameter to set instead of a constant? Or at least bump it to >250?

**Comment by scaryghost** [comment]
Increasing the constant to 250ms is fine.  I don't want it set too high or else the initialization timeout will end up being 15+ seconds which is over kill.

**Comment by hbldh** [comment]
I understand and agree. Currently I replace [150 with 300](https://github.com/hbldh/pymetawear/blob/develop/setup.py#L68-L75) before compiling MetaWear-CppAPI, so there is no immediate need to bump it to a higher value just to get something to work.
